# application-local.yml
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL:jdbc:mysql://52.79.65.128:3306/korailTalk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${LOCAL_DB_USERNAME:root}
    password: ${LOCAL_DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE

springdoc:
  swagger-ui:
    enabled: true   # Swagger UI 활성화
    path: /swagger-ui.html  # Swagger UI 접속 경로
    operations-sorter: method  # 메서드 기준 정렬
    tags-sorter: alpha  # 태그를 알파벳순으로 정렬
  api-docs:
    path: /v3/api-docs  # OpenAPI 문서의 기본 경로 설정
  show-actuator: true  # Actuator 관련 문서도 Swagger에서 표시

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}

app:
  server:
    url: ${SWAGGER_BASE_URL:http://localhost:8080}